# Generated by Django 3.1.6 on 2021-02-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('number', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('height', models.DateField()),
                ('weight', models.IntegerField(null=True)),
                ('college', models.CharField(max_length=50)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
    ]
