# Generated by Django 3.1.6 on 2021-02-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='college',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='height',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='number',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='position',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='salary',
            new_name='Salary',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='team',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='weight',
            new_name='Weight',
        ),
    ]
