# Generated by Django 3.1.6 on 2021-02-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchAPIApp', '0002_auto_20210217_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='Salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
